// <auto-generated />
using Configuration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Configuration.Data.Migrations
{
    [DbContext(typeof(ConfigurationContext))]
    partial class ConfigurationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Configuration.Data.Models.ConfigurationValue", b =>
                {
                    b.Property<string>("Key")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Value");

                    b.HasKey("Key");

                    b.ToTable("ConfigurationValues");

                    b.HasData(
                        new { Key = "http", Value = "http://localhost:5000" },
                        new { Key = "https", Value = "https://localhost:5001" },
                        new { Key = "ConfigurationConnectionStringDB", Value = "Data Source = (localdb)\\MSSQLLocalDB; Initial Catalog = EFConfigurationDB; Integrated Security = True; Connect Timeout = 30; Encrypt = False; TrustServerCertificate = False; ApplicationIntent = ReadWrite; MultiSubnetFailover = False" },
                        new { Key = "ASPNETCORE_ENVIRONMENT", Value = "Development" },
                        new { Key = "Open Ports", Value = "2011, 2456, 8885" },
                        new { Key = "sslPort", Value = "44303" },
                        new { Key = "TestUser", Value = "John Smith" },
                        new { Key = "TestUserGuid", Value = "d4acd337-5915-4e32-b978-6d216e8b0353" },
                        new { Key = "Complex:Name", Value = "Marcel Proust" },
                        new { Key = "Complex:Email", Value = "marcelproust@france.fr" },
                        new { Key = "Complex:Position", Value = "Writer" },
                        new { Key = "Complex:DateOfBirth", Value = "10 July 1871" },
                        new { Key = "Complex:DateOfDeath", Value = "18 November 1922" },
                        new { Key = "Complex:Address:Street", Value = "Avenue des Champs - Élysées 49" },
                        new { Key = "Complex:Address:City", Value = "Paris" },
                        new { Key = "Complex:Address:Zipcode", Value = "75008" },
                        new { Key = "Complex:Address:Country", Value = "France" },
                        new { Key = "Complex:Department:Production", Value = "Production Department" },
                        new { Key = "Complex:Department:Research", Value = "Research and Development Department" },
                        new { Key = "Complex:Department:Purchasing", Value = "Purchasing Department" },
                        new { Key = "Complex:Department:Marketing", Value = "Marketing and Sales Department" },
                        new { Key = "Complex:Department:HumanResources", Value = "Human Resources Management Department" },
                        new { Key = "Complex:Department:Finance", Value = "Accounting and Finance Department" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
